apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "template_name" . }}
  labels:
    app: {{ template "template_name" . }}
    chart: {{ template "chart_name" . }}
    release: {{ .Release.Name }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: {{ .Values.configuration.replicas }}
  selector:
    matchLabels:
      app: {{ template "template_name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "template_name" . }}
        release: {{ .Release.Name }}
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '1234'
    spec:
      containers:
        - name: {{ template "template_name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
{{- range $name, $value := .Values.configuration.env }}
            - name: "{{ $name }}"
              value: "{{ $value }}"
{{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            {{  range .Values.configuration.args }}
            - {{ . }}
            {{ end }}
          resources:
  {{ toYaml .Values.configuration.resources | indent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: 1234
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: /health
              port: 1234
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}